# Generated by Django 5.0.2 on 2024-03-04 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_promaxima', '0002_dadosraspados_delete_tabelas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosraspados',
            name='comprador',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dadosraspados',
            name='objeto',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dadosraspados',
            name='quantidade',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dadosraspados',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
