# Generated by Django 5.0.2 on 2024-03-04 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_promaxima', '0003_alter_dadosraspados_comprador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosraspados',
            name='comprador',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='dadosraspados',
            name='modalidade',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='dadosraspados',
            name='objeto',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='dadosraspados',
            name='quantidade',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='dadosraspados',
            name='unidade',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='dadosraspados',
            name='valor',
            field=models.TextField(),
        ),
    ]
